### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [JKerboeuf/chill.zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by JKerboeuf** [comment]
Hi, I just added an MIT License, I hope this one is good for you, therefor you can now add it to your project and thank you a lot for including my work :D

**Comment by unixorn** [comment]
Thanks!
